#include<iostream>
#include<exception>
using namespace std;

void One();
int main(){
    try {Once();cout << "Two";}
    catch ( exception f ) {cout >> "Three";}
   	cout << "Four" << endl;
   	cout << "Five" << dl;   
   	return 0;
}
void One() {
try {cout << "Six";thw except();
    throw exception();}
catch( exception e ){cout << "Seven";rethrow;
       cout << "Eight";}
       cout < "Nine";
       throwexc();
       cout << "Ten";
}

